=== calzada/PARLAMINT-ES-MC/CD/cd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- cd.dtd by Fer 141214 -->

<!ELEMENT ecpc_CD (header, body, back)>

<!ELEMENT header (legislature, title, label, date, place, edition, index)>
<!ATTLIST header filename CDATA #REQUIRED>
<!ATTLIST header language CDATA #REQUIRED>

<!ELEMENT legislature (#PCDATA)>
<!ATTLIST legislature begin CDATA #REQUIRED>
<!ATTLIST legislature end CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT label (#PCDATA|omit)*>
<!ELEMENT date (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT edition (#PCDATA)>

<!ELEMENT index (indexitem+)>
<!ELEMENT indexitem (#PCDATA | omit | page_number)*>
<!ELEMENT page_number (#PCDATA)>
<!ELEMENT omit (#PCDATA | page_number|omit)*>
<!ATTLIST omit type CDATA #REQUIRED>

<!ELEMENT body (chair | omit)+>
<!ELEMENT chair (heading | intervention | omit)*>
<!ATTLIST chair who CDATA #REQUIRED>

<!ELEMENT heading (#PCDATA | omit|page_number)*>
<!ATTLIST heading number CDATA #REQUIRED>
<!-- <!ATTLIST heading number ID #REQUIRED> -->

<!ELEMENT intervention (speaker, speech)>
<!ATTLIST intervention id CDATA #REQUIRED>
<!-- <!ATTLIST intervention id ID #REQUIRED> when numbered -->
<!ELEMENT speaker (name,birth_date,birth_place,status,gender,institution,constituency,affiliation,post)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT birth_date (#PCDATA)>
<!ELEMENT birth_place (#PCDATA)>
<!ATTLIST birth_place country CDATA #REQUIRED>
<!ELEMENT status (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT institution (ni|io|ngo|vip) >
<!ELEMENT ni (#PCDATA) >
<!ATTLIST ni country (ES|UNKNOWN|NA|NON-ES) #REQUIRED >
<!ELEMENT io (#PCDATA) >
<!ELEMENT ngo (#PCDATA) >
<!ELEMENT vip (#PCDATA) >
<!ELEMENT constituency EMPTY>
<!ATTLIST constituency country (ES|NON-ES) #REQUIRED>
<!ATTLIST constituency region CDATA #REQUIRED>
<!ELEMENT affiliation (national_party,cd) >
<!ELEMENT cd EMPTY>
<!ATTLIST cd group CDATA #REQUIRED>
<!ELEMENT national_party (#PCDATA) >
<!ELEMENT post (#PCDATA)>
<!ELEMENT speech (#PCDATA | omit | page_number)*>
<!ATTLIST speech language NMTOKEN #FIXED "ES">
<!ATTLIST speech id CDATA #REQUIRED>
<!-- <!ATTLIST speech id ID #REQUIRED> when numbered -->

<!ELEMENT back (#PCDATA)>

=== calzada/PARLAMINT-ES-MC/CD/CD200722.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ecpc_CD SYSTEM "cd.dtd">
<ecpc_CD>

<header filename="CD20200722" language="ES">
<legislature begin="20191203" end="at present">XIV</legislature>
<title>CORTES GENERALES DIARIO DE SESIONES DEL CONGRESO DE LOS DIPUTADOS PLENO Y DIPUTACIÓN PERMANENTE</title>
<label>Sesión plenaria núm. 36 <omit type="comment">extraordinaria</omit></label>
<date>20200722</date>
<place>CORTES GENERALES</place>
<edition>online</edition>   
<index>
<indexitem>ORDEN DEL DÍA 
Preguntas ... <page_number>Página 5</page_number> 
Dictámenes de comisiones no permanentes. <omit type="comment">Votación</omit>: 
- Dictamen de la Comisión para la Reconstrucción Social y Económica. <omit type="comment">Número de expediente 153/000001</omit> ... <page_number>Página 25</page_number> 
Convalidación o derogación de reales decretos-leyes. <omit type="comment">Votación</omit>: 
- Real Decreto-ley 26/2020, de 7 de julio, de medidas de reactivación económica para hacer frente al impacto del COVID-19 en los ámbitos de transportes y vivienda. <omit type="comment">'BOE' núm. 187, de 8 de julio de 2020</omit>. <omit type="comment">Número de expediente 130/000027</omit> ... <page_number>Página 27</page_number> 
Dictámenes de la Comisión del Estatuto de los Diputados. <omit type="comment">Votación</omit>: 
- Dictamen de la Comisión del Estatuto de los Diputados sobre declaración de actividades de excelentísimos señores diputados. <omit type="comment">Número de expediente 042/000010</omit> ... <page_number>Página 28</page_number> 
<page_number>Página 2</page_number> 
</indexitem>
<indexitem>SUMARIO 
Se reanuda la sesión a las nueve de la mañana. 
Preguntas ... <page_number>Página 5</page_number> 
Del diputado don Pablo Casado Blanco, del Grupo Parlamentario Popular en el Congreso, que formula al señor presidente del Gobierno: ¿Cómo valora la situación por la que están atravesando los españoles? <omit type="comment">Número de expediente 180/000246</omit> ... <page_number>Página 5</page_number> 
Del diputado don Edmundo Bal Francés, del Grupo Parlamentario Ciudadanos, que formula al señor presidente del Gobierno: ¿Qué valoración hace de la evolución de la pandemia y de la respuesta que se está dando tanto a nivel nacional como europeo? <omit type="comment">Número de expediente 180/000243</omit> ... <page_number>Página 7</page_number> 
Del diputado don Aitor Esteban Bravo, del Grupo Parlamentario Vasco <omit type="comment">EAJ-PNV</omit>, que formula al señor presidente del Gobierno: ¿Piensa seguir obviando la relación bilateral entre el Estado y la Comunidad Autónoma del País Vasco retrasando la convocatoria de la Comisión Mixta del Concierto Económico que debe establecer los límites de déficit y deuda para las administraciones vascas? <omit type="comment">Número de expediente 180/000242</omit> ... <page_number>Página 8</page_number> 
De la diputada doña Cayetana Álvarez de Toledo Peralta-Ramos, del Grupo Parlamentario Popular en el Congreso, que formula a la señora vicepresidenta primera y ministra de la Presidencia, Relaciones con las Cortes y Memoria Democrática: ¿Qué está haciendo el Gobierno para defender la Constitución? <omit type="comment">Número de expediente 180/000247</omit> ... <page_number>Página 9</page_number> 
Del diputado don Jon Iñarritu García, del Grupo Parlamentario Euskal Herria Bildu, que formula a la señora vicepresidenta primera y ministra de la Presidencia, Relaciones con las Cortes y Memoria Democrática: ¿Qué más tendría que ocurrir para que el Gobierno apoyara la celebración de un referéndum sobre la Jefatura del Estado? <omit type="comment">Número de expediente 180/000245</omit> ... <page_number>Página 11</page_number> 
Del diputado don Teodoro García Egea, del Grupo Parlamentario Popular en el Congreso, que formula al señor vicepresidente segundo y ministro de Derechos Sociales y Agenda 2030: ¿Qué autocrítica hace el vicepresidente segundo de su labor de Gobierno? <omit type="comment">Número de expediente 180/000248</omit> ... <page_number>Página 12</page_number> 
De la diputada doña Macarena Olona Choclán, del Grupo Parlamentario VOX, que formula a la señora vicepresidenta primera y ministra de la Presidencia, Relaciones con las Cortes y Memoria Democrática: ¿Considera que incumbe al Gobierno el llamado 'caso Dina'? <omit type="comment">Número de expediente 180/000252</omit> ... <page_number>Página 14</page_number> 
<page_number>Página 3</page_number> 
Del diputado don Ignacio Gil Lázaro, del Grupo Parlamentario VOX, que formula al señor ministro del Interior: ¿Va a instar el Gobierno al Ministerio Fiscal para que recurra la concesión del tercer grado penitenciario a los condenados en la causa especial 20907/2017? <omit type="comment">Número de expediente 180/000254</omit> ... <page_number>Página 15</page_number> 
Del diputado don Iván Espinosa de los Monteros de Simón, del Grupo Parlamentario VOX, que formula a la señora ministra de Hacienda: ¿Genera desconfianza en nuestros socios europeos de cara a la negociación de los fondos de reconstrucción el hecho de la presencia de ministros comunistas en el Gobierno de España? <omit type="comment">Número de expediente 180/000253</omit> ... <page_number>Página 16</page_number> 
Del diputado don Gabriel Rufián Romero, del Grupo Parlamentario Republicano, que formula al Gobierno: ¿Desde el Gobierno español se ha espiado a cargos políticos? <omit type="comment">Número de expediente 180/000244</omit> ... <page_number>Página 18</page_number> 
De la diputada doña Concepción Gamarra Ruiz-Clavijo, del Grupo Parlamentario Popular en el Congreso, que formula al señor ministro de Sanidad: ¿Qué está haciendo el Gobierno para controlar los rebrotes del COVID-19? <omit type="comment">Número de expediente 180/000250</omit> ... <page_number>Página 19</page_number> 
Del diputado don Isidro Manuel Martínez Oblanca, del Grupo Parlamentario Mixto, que formula al Gobierno: ¿Qué medidas de emergencia piensa adoptar el Gobierno para dar solución al colapso económico-administrativo que ha sumido a la plantilla y a los centros del Instituto Español de Oceanografía <omit type="comment">IEO</omit>, entre ellos el de Gijón <omit type="comment">Asturias</omit>, en la mayor crisis de su historia, comprometiendo gravemente el desarrollo de las investigaciones sobre el mar y sus recursos? <omit type="comment">Número de expediente 180/000240</omit> ... <page_number>Página 20</page_number> 
De la diputada doña Belén Hoyo Juliá, del Grupo Parlamentario Popular en el Congreso, que formula a la señora ministra de Igualdad: ¿Qué es para usted una conducta machista? <omit type="comment">Número de expediente 180/000249</omit> ... <page_number>Página 21</page_number> 
Del diputado don José Alberto Herrero Bono, del Grupo Parlamentario Popular en el Congreso, que formula a la señora ministra de Industria, Comercio y Turismo: ¿Qué está haciendo el Gobierno para atajar la crisis del sector turístico? <omit type="comment">Número de expediente 180/000251</omit> ... <page_number>Página 23</page_number> 
Del diputado don Néstor Rego Candamil, del Grupo Parlamentario Plural, que formula a la señora ministra de Industria, Comercio y Turismo: ¿Contempla el Gobierno la intervención pública de Alcoa para nacionalizar la planta de San Cibrao? <omit type="comment">Número de expediente 180/000241</omit> ... <page_number>Página 24</page_number> 
<page_number>Página 4</page_number> 
Dictámenes de comisiones no permanentes. <omit type="comment">Votación</omit> ... <page_number>Página 25</page_number> 
La Presidencia da cuenta a la Cámara de las enmiendas que han sido aprobadas en relación con cada parte del dictamen de la Comisión para la Reconstrucción Social y Económica tras la conclusión de la votación telemática. 
La Presidencia informa de que desde las diez y media de la mañana hasta las doce del mediodía de hoy se podrá votar telemáticamente el dictamen de la Comisión para la Reconstrucción Social y Económica y el resto de puntos del orden del día. 
Se suspende la sesión a las diez y treinta y cinco minutos de la mañana. 
Se reanuda la sesión a las doce y quince minutos del mediodía. 
Se somete a votación el dictamen de la Comisión para la Reconstrucción Social y Económica: 
Sometido a votación el texto del dictamen sobre Sanidad y Salud Pública, se aprueba por 115 votos a favor más 141 votos telemáticos, 256; 30 en contra más 58 votos telemáticos, 88; y 3 abstenciones con voto telemático. 
Sometido a votación el texto del dictamen sobre Reactivación Económica, se aprueba por 75 votos a favor más 94 votos telemáticos, 169; 70 en contra más 98 votos telemáticos, 168; y 1 abstención más 10 votos telemáticos, 11. 
Sometido a votación el texto del dictamen sobre Políticas Sociales y Sistema de Cuidados, se rechaza por 77 votos a favor más 95 votos telemáticos, 172; 68 en contra más 107 votos telemáticos, 175; y 1 abstención. 
Sometido a votación el texto del dictamen sobre Unión europea, se aprueba por 119 votos a favor más 157 votos telemáticos, 276; en contra 25 más 34 votos telemáticos, 59; y 2 abstenciones más 11 votos telemáticos, 13. 
Sometida a votación la posición particular número 1, Grupo Parlamentario Popular en el Congreso, se rechaza por 42 votos a favor más 52 votos telemáticos, 94; en contra 80 más 110 votos telemáticos, 190; y 11 abstenciones con voto telemático. 
Sometida a votación la posición particular número 2, Grupo Parlamentario Republicano, se rechaza por 3 votos a favor más 18 votos telemáticos, 21; 118 en contra más 144 votos telemáticos, 262; y 1 abstención más 11 votos telemáticos, 12. 
Sometida a votación la posición particular número 3, Grupo Parlamentario Ciudadanos, se rechaza por 41 votos a favor más 60 votos telemáticos, 101; 81 en contra más 110 votos telemáticos, 191; y 3 abstenciones con voto telemático. 
Convalidación o derogación de reales decretos-leyes. <omit type="comment">Votación</omit> ... <page_number>Página 27</page_number>
